version: "2.2"

services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"
    profiles:
    - mysql
  postgres:
    image: postgres:15.3
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=petclinic
      - POSTGRES_USER=petclinic
      - POSTGRES_DB=petclinic
    profiles:
    - postgres
  petclinic:
    # image: spring-petclinic:3.1.0-SNAPSHOT
    image: mypetclinic
    ports:
      - "8080:8080"
    environment:
      - CONTRAST__API__API_KEY=${CONTRAST__API__API_KEY}
      - CONTRAST__API__SERVICE_KEY=${CONTRAST__API__SERVICE_KEY}
      - CONTRAST__API__USER_NAME=${CONTRAST__API__USER_NAME}
      - CONTRAST__API__URL=https://intuit.contrastsecurity.com/Contrast
      - CONTRAST__APPLICATION__NAME="petclinic_${EMAIL}"
    depends_on:
      - mysql
      - postgres
    profiles:
      - mysql
      - postgres
